__version__: 1.1.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
