class_name: tumor.dataset.base_dataset.BrainData
train:
  params:
    data_path: /workspace/data/tw2
    df: /workspace/data/tw2/train_0.csv
    num_ex: 19
    color_code: 6
val:
  params:
    data_path: /workspace/data/tw2
    df: /workspace/data/tw2/val_0.csv
    num_ex: 19
    color_code: 6
