save_path: /workspace/data/small_flair
data_path: /workspace/data/small_data
projections: ["FLAIR"]
img_size: [512, 512]
voi_lut: true
base_df: /workspace/data/small_data.csv
split: cross-validation
split_params:
  n_folds: 2